FROM centos:7

RUN yum -y update && \
    yum -y install epel-release && \
    yum -y install nginx

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
# Start nginx service
CMD ["nginx", "-g", "daemon off;"]
